//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarHireServiceConsumer.CarHireService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car", Namespace="http://schemas.datacontract.org/2004/07/CarHireDataAccess.Models.Vehicles")]
    [System.SerializableAttribute()]
    public partial class Car : CarHireServiceConsumer.CarHireService.Vehicle {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumDoorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumSeatsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumDoors {
            get {
                return this.NumDoorsField;
            }
            set {
                if ((this.NumDoorsField.Equals(value) != true)) {
                    this.NumDoorsField = value;
                    this.RaisePropertyChanged("NumDoors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumSeats {
            get {
                return this.NumSeatsField;
            }
            set {
                if ((this.NumSeatsField.Equals(value) != true)) {
                    this.NumSeatsField = value;
                    this.RaisePropertyChanged("NumSeats");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vehicle", Namespace="http://schemas.datacontract.org/2004/07/CarHireDataAccess.Models.Vehicles")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CarHireServiceConsumer.CarHireService.Car))]
    public partial class Vehicle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColourHexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EngineSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAutomaticField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ManufactureDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarHireServiceConsumer.CarHireService.Manufacturer ManufacturerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ManufacturerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegistrationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarHireServiceConsumer.CarHireService.StoreLocation StoreLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid StoreLocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarHireServiceConsumer.CarHireService.VehicleType TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid VehicleIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColourHex {
            get {
                return this.ColourHexField;
            }
            set {
                if ((object.ReferenceEquals(this.ColourHexField, value) != true)) {
                    this.ColourHexField = value;
                    this.RaisePropertyChanged("ColourHex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EngineSize {
            get {
                return this.EngineSizeField;
            }
            set {
                if ((object.ReferenceEquals(this.EngineSizeField, value) != true)) {
                    this.EngineSizeField = value;
                    this.RaisePropertyChanged("EngineSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAutomatic {
            get {
                return this.IsAutomaticField;
            }
            set {
                if ((this.IsAutomaticField.Equals(value) != true)) {
                    this.IsAutomaticField = value;
                    this.RaisePropertyChanged("IsAutomatic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ManufactureDate {
            get {
                return this.ManufactureDateField;
            }
            set {
                if ((this.ManufactureDateField.Equals(value) != true)) {
                    this.ManufactureDateField = value;
                    this.RaisePropertyChanged("ManufactureDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarHireServiceConsumer.CarHireService.Manufacturer Manufacturer {
            get {
                return this.ManufacturerField;
            }
            set {
                if ((object.ReferenceEquals(this.ManufacturerField, value) != true)) {
                    this.ManufacturerField = value;
                    this.RaisePropertyChanged("Manufacturer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ManufacturerId {
            get {
                return this.ManufacturerIdField;
            }
            set {
                if ((this.ManufacturerIdField.Equals(value) != true)) {
                    this.ManufacturerIdField = value;
                    this.RaisePropertyChanged("ManufacturerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelName {
            get {
                return this.ModelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelNameField, value) != true)) {
                    this.ModelNameField = value;
                    this.RaisePropertyChanged("ModelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Registration {
            get {
                return this.RegistrationField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistrationField, value) != true)) {
                    this.RegistrationField = value;
                    this.RaisePropertyChanged("Registration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarHireServiceConsumer.CarHireService.StoreLocation StoreLocation {
            get {
                return this.StoreLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreLocationField, value) != true)) {
                    this.StoreLocationField = value;
                    this.RaisePropertyChanged("StoreLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid StoreLocationId {
            get {
                return this.StoreLocationIdField;
            }
            set {
                if ((this.StoreLocationIdField.Equals(value) != true)) {
                    this.StoreLocationIdField = value;
                    this.RaisePropertyChanged("StoreLocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarHireServiceConsumer.CarHireService.VehicleType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid VehicleId {
            get {
                return this.VehicleIdField;
            }
            set {
                if ((this.VehicleIdField.Equals(value) != true)) {
                    this.VehicleIdField = value;
                    this.RaisePropertyChanged("VehicleId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Manufacturer", Namespace="http://schemas.datacontract.org/2004/07/CarHireDataAccess.Models.Vehicles")]
    [System.SerializableAttribute()]
    public partial class Manufacturer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ManufacturerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManufacturerNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ManufacturerId {
            get {
                return this.ManufacturerIdField;
            }
            set {
                if ((this.ManufacturerIdField.Equals(value) != true)) {
                    this.ManufacturerIdField = value;
                    this.RaisePropertyChanged("ManufacturerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManufacturerName {
            get {
                return this.ManufacturerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ManufacturerNameField, value) != true)) {
                    this.ManufacturerNameField = value;
                    this.RaisePropertyChanged("ManufacturerName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StoreLocation", Namespace="http://schemas.datacontract.org/2004/07/CarHireDataAccess.Models.Locations")]
    [System.SerializableAttribute()]
    public partial class StoreLocation : CarHireServiceConsumer.CarHireService.Location {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarHireServiceConsumer.CarHireService.BusinessHours[] BusinessHoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StoreNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarHireServiceConsumer.CarHireService.Vehicle[] VehiclesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarHireServiceConsumer.CarHireService.BusinessHours[] BusinessHours {
            get {
                return this.BusinessHoursField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessHoursField, value) != true)) {
                    this.BusinessHoursField = value;
                    this.RaisePropertyChanged("BusinessHours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StoreName {
            get {
                return this.StoreNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreNameField, value) != true)) {
                    this.StoreNameField = value;
                    this.RaisePropertyChanged("StoreName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelephoneNumber {
            get {
                return this.TelephoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneNumberField, value) != true)) {
                    this.TelephoneNumberField = value;
                    this.RaisePropertyChanged("TelephoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarHireServiceConsumer.CarHireService.Vehicle[] Vehicles {
            get {
                return this.VehiclesField;
            }
            set {
                if ((object.ReferenceEquals(this.VehiclesField, value) != true)) {
                    this.VehiclesField = value;
                    this.RaisePropertyChanged("Vehicles");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleType", Namespace="http://schemas.datacontract.org/2004/07/CarHireDataAccess.Models.Vehicles")]
    public enum VehicleType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Car = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Van = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PeopleCarrier = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SUV = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/CarHireDataAccess.Models.Locations")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CarHireServiceConsumer.CarHireService.StoreLocation))]
    public partial class Location : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarHireServiceConsumer.CarHireService.Address AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid LocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double latitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double longtitudeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarHireServiceConsumer.CarHireService.Address Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid LocationId {
            get {
                return this.LocationIdField;
            }
            set {
                if ((this.LocationIdField.Equals(value) != true)) {
                    this.LocationIdField = value;
                    this.RaisePropertyChanged("LocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double latitude {
            get {
                return this.latitudeField;
            }
            set {
                if ((this.latitudeField.Equals(value) != true)) {
                    this.latitudeField = value;
                    this.RaisePropertyChanged("latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double longtitude {
            get {
                return this.longtitudeField;
            }
            set {
                if ((this.longtitudeField.Equals(value) != true)) {
                    this.longtitudeField = value;
                    this.RaisePropertyChanged("longtitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/CarHireDataAccess.Models.User_Classes")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid AddressIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid[] MemberIDsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AddressID {
            get {
                return this.AddressIDField;
            }
            set {
                if ((this.AddressIDField.Equals(value) != true)) {
                    this.AddressIDField = value;
                    this.RaisePropertyChanged("AddressID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string County {
            get {
                return this.CountyField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyField, value) != true)) {
                    this.CountyField = value;
                    this.RaisePropertyChanged("County");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line1 {
            get {
                return this.Line1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line1Field, value) != true)) {
                    this.Line1Field = value;
                    this.RaisePropertyChanged("Line1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line2 {
            get {
                return this.Line2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line2Field, value) != true)) {
                    this.Line2Field = value;
                    this.RaisePropertyChanged("Line2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line3 {
            get {
                return this.Line3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line3Field, value) != true)) {
                    this.Line3Field = value;
                    this.RaisePropertyChanged("Line3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid[] MemberIDs {
            get {
                return this.MemberIDsField;
            }
            set {
                if ((object.ReferenceEquals(this.MemberIDsField, value) != true)) {
                    this.MemberIDsField = value;
                    this.RaisePropertyChanged("MemberIDs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Postcode {
            get {
                return this.PostcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostcodeField, value) != true)) {
                    this.PostcodeField = value;
                    this.RaisePropertyChanged("Postcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Town {
            get {
                return this.TownField;
            }
            set {
                if ((object.ReferenceEquals(this.TownField, value) != true)) {
                    this.TownField = value;
                    this.RaisePropertyChanged("Town");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessHours", Namespace="http://schemas.datacontract.org/2004/07/CarHireDataAccess.Models.Locations")]
    [System.SerializableAttribute()]
    public partial class BusinessHours : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ClosingTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarHireServiceConsumer.CarHireService.Day DayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid LocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OpeningTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ClosingTime {
            get {
                return this.ClosingTimeField;
            }
            set {
                if ((this.ClosingTimeField.Equals(value) != true)) {
                    this.ClosingTimeField = value;
                    this.RaisePropertyChanged("ClosingTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarHireServiceConsumer.CarHireService.Day Day {
            get {
                return this.DayField;
            }
            set {
                if ((this.DayField.Equals(value) != true)) {
                    this.DayField = value;
                    this.RaisePropertyChanged("Day");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid LocationId {
            get {
                return this.LocationIdField;
            }
            set {
                if ((this.LocationIdField.Equals(value) != true)) {
                    this.LocationIdField = value;
                    this.RaisePropertyChanged("LocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OpeningTime {
            get {
                return this.OpeningTimeField;
            }
            set {
                if ((this.OpeningTimeField.Equals(value) != true)) {
                    this.OpeningTimeField = value;
                    this.RaisePropertyChanged("OpeningTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Day", Namespace="http://schemas.datacontract.org/2004/07/CarHireDataAccess.Models.Locations")]
    public enum Day : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Monday = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tuesday = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Wednesday = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Thursday = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Friday = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Saturday = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sunday = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CarHireService.ICarHireServiceSoap")]
    public interface ICarHireServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarHireServiceSoap/Test", ReplyAction="http://tempuri.org/ICarHireServiceSoap/TestResponse")]
        string Test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarHireServiceSoap/Test", ReplyAction="http://tempuri.org/ICarHireServiceSoap/TestResponse")]
        System.Threading.Tasks.Task<string> TestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarHireServiceSoap/GetAllCars", ReplyAction="http://tempuri.org/ICarHireServiceSoap/GetAllCarsResponse")]
        CarHireServiceConsumer.CarHireService.Car[] GetAllCars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarHireServiceSoap/GetAllCars", ReplyAction="http://tempuri.org/ICarHireServiceSoap/GetAllCarsResponse")]
        System.Threading.Tasks.Task<CarHireServiceConsumer.CarHireService.Car[]> GetAllCarsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarHireServiceSoap/GetCarById", ReplyAction="http://tempuri.org/ICarHireServiceSoap/GetCarByIdResponse")]
        CarHireServiceConsumer.CarHireService.Car GetCarById(System.Guid vehicleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarHireServiceSoap/GetCarById", ReplyAction="http://tempuri.org/ICarHireServiceSoap/GetCarByIdResponse")]
        System.Threading.Tasks.Task<CarHireServiceConsumer.CarHireService.Car> GetCarByIdAsync(System.Guid vehicleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarHireServiceSoap/NewCar", ReplyAction="http://tempuri.org/ICarHireServiceSoap/NewCarResponse")]
        void NewCar(CarHireServiceConsumer.CarHireService.Car car);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarHireServiceSoap/NewCar", ReplyAction="http://tempuri.org/ICarHireServiceSoap/NewCarResponse")]
        System.Threading.Tasks.Task NewCarAsync(CarHireServiceConsumer.CarHireService.Car car);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarHireServiceSoap/UpdateCar", ReplyAction="http://tempuri.org/ICarHireServiceSoap/UpdateCarResponse")]
        void UpdateCar(CarHireServiceConsumer.CarHireService.Car car);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarHireServiceSoap/UpdateCar", ReplyAction="http://tempuri.org/ICarHireServiceSoap/UpdateCarResponse")]
        System.Threading.Tasks.Task UpdateCarAsync(CarHireServiceConsumer.CarHireService.Car car);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarHireServiceSoap/DeleteCar", ReplyAction="http://tempuri.org/ICarHireServiceSoap/DeleteCarResponse")]
        void DeleteCar(System.Guid vehicleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarHireServiceSoap/DeleteCar", ReplyAction="http://tempuri.org/ICarHireServiceSoap/DeleteCarResponse")]
        System.Threading.Tasks.Task DeleteCarAsync(System.Guid vehicleId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICarHireServiceSoapChannel : CarHireServiceConsumer.CarHireService.ICarHireServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarHireServiceSoapClient : System.ServiceModel.ClientBase<CarHireServiceConsumer.CarHireService.ICarHireServiceSoap>, CarHireServiceConsumer.CarHireService.ICarHireServiceSoap {
        
        public CarHireServiceSoapClient() {
        }
        
        public CarHireServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarHireServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarHireServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarHireServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Test() {
            return base.Channel.Test();
        }
        
        public System.Threading.Tasks.Task<string> TestAsync() {
            return base.Channel.TestAsync();
        }
        
        public CarHireServiceConsumer.CarHireService.Car[] GetAllCars() {
            return base.Channel.GetAllCars();
        }
        
        public System.Threading.Tasks.Task<CarHireServiceConsumer.CarHireService.Car[]> GetAllCarsAsync() {
            return base.Channel.GetAllCarsAsync();
        }
        
        public CarHireServiceConsumer.CarHireService.Car GetCarById(System.Guid vehicleId) {
            return base.Channel.GetCarById(vehicleId);
        }
        
        public System.Threading.Tasks.Task<CarHireServiceConsumer.CarHireService.Car> GetCarByIdAsync(System.Guid vehicleId) {
            return base.Channel.GetCarByIdAsync(vehicleId);
        }
        
        public void NewCar(CarHireServiceConsumer.CarHireService.Car car) {
            base.Channel.NewCar(car);
        }
        
        public System.Threading.Tasks.Task NewCarAsync(CarHireServiceConsumer.CarHireService.Car car) {
            return base.Channel.NewCarAsync(car);
        }
        
        public void UpdateCar(CarHireServiceConsumer.CarHireService.Car car) {
            base.Channel.UpdateCar(car);
        }
        
        public System.Threading.Tasks.Task UpdateCarAsync(CarHireServiceConsumer.CarHireService.Car car) {
            return base.Channel.UpdateCarAsync(car);
        }
        
        public void DeleteCar(System.Guid vehicleId) {
            base.Channel.DeleteCar(vehicleId);
        }
        
        public System.Threading.Tasks.Task DeleteCarAsync(System.Guid vehicleId) {
            return base.Channel.DeleteCarAsync(vehicleId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CarHireService.ICarHireServiceRest")]
    public interface ICarHireServiceRest {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarHireServiceRest/RestGetAllCars", ReplyAction="http://tempuri.org/ICarHireServiceRest/RestGetAllCarsResponse")]
        CarHireServiceConsumer.CarHireService.Car[] RestGetAllCars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarHireServiceRest/RestGetAllCars", ReplyAction="http://tempuri.org/ICarHireServiceRest/RestGetAllCarsResponse")]
        System.Threading.Tasks.Task<CarHireServiceConsumer.CarHireService.Car[]> RestGetAllCarsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarHireServiceRest/RestGetCarById", ReplyAction="http://tempuri.org/ICarHireServiceRest/RestGetCarByIdResponse")]
        CarHireServiceConsumer.CarHireService.Car RestGetCarById(string vehicleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarHireServiceRest/RestGetCarById", ReplyAction="http://tempuri.org/ICarHireServiceRest/RestGetCarByIdResponse")]
        System.Threading.Tasks.Task<CarHireServiceConsumer.CarHireService.Car> RestGetCarByIdAsync(string vehicleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarHireServiceRest/RestNewCar", ReplyAction="http://tempuri.org/ICarHireServiceRest/RestNewCarResponse")]
        void RestNewCar(CarHireServiceConsumer.CarHireService.Car car);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarHireServiceRest/RestNewCar", ReplyAction="http://tempuri.org/ICarHireServiceRest/RestNewCarResponse")]
        System.Threading.Tasks.Task RestNewCarAsync(CarHireServiceConsumer.CarHireService.Car car);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarHireServiceRest/RestUpdateCar", ReplyAction="http://tempuri.org/ICarHireServiceRest/RestUpdateCarResponse")]
        void RestUpdateCar(CarHireServiceConsumer.CarHireService.Car car);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarHireServiceRest/RestUpdateCar", ReplyAction="http://tempuri.org/ICarHireServiceRest/RestUpdateCarResponse")]
        System.Threading.Tasks.Task RestUpdateCarAsync(CarHireServiceConsumer.CarHireService.Car car);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarHireServiceRest/RestDeleteCar", ReplyAction="http://tempuri.org/ICarHireServiceRest/RestDeleteCarResponse")]
        void RestDeleteCar(string vehicleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarHireServiceRest/RestDeleteCar", ReplyAction="http://tempuri.org/ICarHireServiceRest/RestDeleteCarResponse")]
        System.Threading.Tasks.Task RestDeleteCarAsync(string vehicleId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICarHireServiceRestChannel : CarHireServiceConsumer.CarHireService.ICarHireServiceRest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarHireServiceRestClient : System.ServiceModel.ClientBase<CarHireServiceConsumer.CarHireService.ICarHireServiceRest>, CarHireServiceConsumer.CarHireService.ICarHireServiceRest {
        
        public CarHireServiceRestClient() {
        }
        
        public CarHireServiceRestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarHireServiceRestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarHireServiceRestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarHireServiceRestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CarHireServiceConsumer.CarHireService.Car[] RestGetAllCars() {
            return base.Channel.RestGetAllCars();
        }
        
        public System.Threading.Tasks.Task<CarHireServiceConsumer.CarHireService.Car[]> RestGetAllCarsAsync() {
            return base.Channel.RestGetAllCarsAsync();
        }
        
        public CarHireServiceConsumer.CarHireService.Car RestGetCarById(string vehicleId) {
            return base.Channel.RestGetCarById(vehicleId);
        }
        
        public System.Threading.Tasks.Task<CarHireServiceConsumer.CarHireService.Car> RestGetCarByIdAsync(string vehicleId) {
            return base.Channel.RestGetCarByIdAsync(vehicleId);
        }
        
        public void RestNewCar(CarHireServiceConsumer.CarHireService.Car car) {
            base.Channel.RestNewCar(car);
        }
        
        public System.Threading.Tasks.Task RestNewCarAsync(CarHireServiceConsumer.CarHireService.Car car) {
            return base.Channel.RestNewCarAsync(car);
        }
        
        public void RestUpdateCar(CarHireServiceConsumer.CarHireService.Car car) {
            base.Channel.RestUpdateCar(car);
        }
        
        public System.Threading.Tasks.Task RestUpdateCarAsync(CarHireServiceConsumer.CarHireService.Car car) {
            return base.Channel.RestUpdateCarAsync(car);
        }
        
        public void RestDeleteCar(string vehicleId) {
            base.Channel.RestDeleteCar(vehicleId);
        }
        
        public System.Threading.Tasks.Task RestDeleteCarAsync(string vehicleId) {
            return base.Channel.RestDeleteCarAsync(vehicleId);
        }
    }
}
